version: '3.9'

services:
  web:
    build: .
    command: gunicorn rentex.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - DEBUG=False

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A rentex worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A rentex beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - web

volumes:
  media_volume:
  static_volume:
